export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className="min-h-screen bg-background flex items-center justify-center p-4">
			<div className="w-full max-w-md">
				<div className="bg-background bbb rounded-lg shadow-lg p-6">{children}</div>
			</div>
		</div>
	);
}
