version: '3.8'

services:
  nextjs:
    build:
      target: deps
    command: sh -c "echo -e '\\033[1;35m🔥 Starting Next.js in development mode...\\033[0m' && pnpm dev"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.ts:/app/next.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./.next:/app/.next
    ports:
      - "${PORT:-3000}:3000"

  # Development tools can be added here
  adminer:
    container_name: raioa-adminer
    image: adminer:latest
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - raioa-network
    profiles:
      - postgres
    depends_on:
      - postgres 