import {
  Code,
  Terminal,
  GitBranch,
  Activity,
  Settings2,
  Home,
  LayoutDashboard,
  User,
  MessageSquare,
  FileText,
  Sliders,
} from "lucide-react"
import type { SearchItem } from "../types"

// This configuration file makes it easy to edit shortcuts and actions
export const searchItemsConfig: SearchItem[] = [
  // Routes/Pages
  {
    id: "home",
    title: "Home",
    description: "Return to the main dashboard",
    icon: Home,
    shortcut: "⌘ H",
    altShortcut: "Alt + 1",
    type: "route",
    category: "page",
    path: "/",
  },
  {
    id: "dashboard",
    title: "Dashboard",
    description: "View your personalized dashboard",
    icon: LayoutDashboard,
    type: "route",
    altShortcut: "Alt + 2",
    category: "page",
    path: "/dashboard",
  },
  {
    id: "profile",
    title: "Profile",
    description: "View and edit your profile",
    icon: User,
    type: "route",
    altShortcut: "Alt + 3",
    category: "page",
    path: "/profile",
  },
  {
    id: "messages",
    title: "Messages",
    description: "View your messages and notifications",
    icon: MessageSquare,
    type: "route",
    altShortcut: "Alt + 4",
    category: "page",
    badge: "3",
    path: "/messages",
  },
  {
    id: "docs",
    title: "Documentation",
    description: "View system documentation and guides",
    icon: FileText,
    type: "route",
    altShortcut: "Alt + 5",
    category: "page",
    path: "/docs",
  },

  // Actions/Features
  {
    id: "editor",
    title: "Script Editor",
    description: "Create and edit scripts, tools, and applications",
    icon: Code,
    shortcut: "⌘ E",
    altShortcut: "Alt + 6",
    type: "action",
    category: "feature",
    badge: "Dev",
  },
  {
    id: "terminal",
    title: "Terminal",
    description: "Command-line interface for system operations",
    icon: Terminal,
    shortcut: "⌘ T",
    altShortcut: "Alt + 7",
    type: "action",
    category: "feature",
  },
  {
    id: "git",
    title: "Git Control",
    description: "Manage source code and version control",
    icon: GitBranch,
    shortcut: "⌘ G",
    altShortcut: "Alt + 8",
    type: "action",
    category: "feature",
    badge: "Dev",
  },
  {
    id: "activity",
    title: "Activity Monitor",
    description: "System performance and resource usage",
    icon: Activity,
    shortcut: "⌘ A",
    altShortcut: "Alt + 9",
    type: "action",
    category: "system",
  },
  {
    id: "settings",
    title: "System Settings",
    description: "Configure system preferences and options",
    icon: Settings2,
    shortcut: "⌘ ,",
    altShortcut: "Alt + 0",
    type: "action",
    category: "system",
  },
  {
    id: "palette-settings",
    title: "Command Palette Settings",
    description: "Configure command palette preferences",
    icon: Sliders,
    shortcut: "⌘ P",
    type: "action",
    category: "system",
  },
]

// Map keyboard shortcuts to action IDs
export const keyboardShortcutsMap: Record<string, string> = {
  // Command/Ctrl shortcuts
  e: "editor",
  t: "terminal",
  g: "git",
  a: "activity",
  ",": "settings",
  h: "home",
  p: "palette-settings",

  // Alt + number shortcuts
  "alt+1": "home",
  "alt+2": "dashboard",
  "alt+3": "profile",
  "alt+4": "messages",
  "alt+5": "docs",
  "alt+6": "editor",
  "alt+7": "terminal",
  "alt+8": "git",
  "alt+9": "activity",
  "alt+0": "settings",
}
