import Header from '@/components/layout/header';
import { Toaster } from '@/components/ui/toast';
import { getCurrentUser } from '@/features/authentication/queries/get-current-user';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header user={user} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
