import type { Metadata } from 'next'

export const siteMetadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    // Add more metadata fields here as needed
    // metadataBase: new URL('https://example.com'),
    // openGraph: {
    //   title: 'Your App Title',
    //   description: 'Your app description',
    //   images: ['/og-image.jpg'],
    // },
    // twitter: {
    //   card: 'summary_large_image',
    //   title: 'Your App Title',
    //   description: 'Your app description',
    //   images: ['/twitter-image.jpg'],
    // }
} 