import type { RoadmapItem, RoadmapLane, RoadmapUser } from '../types'

export const mockUsers: RoadmapUser[] = [
	{
		id: 'user-1',
		name: 'John Doe',
		email: 'john@example.com',
		role: 'admin',
		avatarUrl: 'https://github.com/remcostoeten.png',
	},
	{
		id: 'user-2',
		name: 'Jane Smith',
		email: 'jane@example.com',
		role: 'contributor',
		avatarUrl: 'https://github.com/remcostoeten.png',
	},
	{
		id: 'user-3',
		name: 'Bob Johnson',
		email: 'bob@example.com',
		role: 'user',
	},
]

export const mockRoadmapItems: RoadmapItem[] = [
	{
		id: 'item-1',
		title: 'Implement passwordless authentication',
		description: 'Add support for magic links and one-time passwords for passwordless login.',
		status: 'planned',
		priority: 'high',
		category: 'feature',
		createdAt: '2024-03-01T12:00:00Z',
		updatedAt: '2024-03-01T12:00:00Z',
		createdBy: 'user-1',
		assignedTo: 'user-2',
		dueDate: '2024-04-15T00:00:00Z',
		votes: 12,
		comments: [
			{
				id: 'comment-1',
				content: 'We should consider using the Web Authentication API for this.',
				createdAt: '2024-03-02T14:30:00Z',
				createdBy: 'user-2',
			},
		],
		tags: ['authentication', 'security', 'ux'],
	},
	{
		id: 'item-2',
		title: 'Add WebAuthn support',
		description: 'Implement WebAuthn for passwordless authentication using security keys and biometrics.',
		status: 'in-progress',
		priority: 'medium',
		category: 'feature',
		createdAt: '2024-03-05T09:15:00Z',
		updatedAt: '2024-03-10T11:20:00Z',
		createdBy: 'user-1',
		assignedTo: 'user-1',
		votes: 8,
		comments: [],
		tags: ['authentication', 'security', 'webauthn'],
	},
	{
		id: 'item-3',
		title: 'Optimize token validation',
		description: 'Improve performance of JWT token validation by implementing caching.',
		status: 'completed',
		priority: 'medium',
		category: 'performance',
		createdAt: '2024-02-20T10:00:00Z',
		updatedAt: '2024-03-05T16:45:00Z',
		createdBy: 'user-2',
		votes: 5,
		comments: [
			{
				id: 'comment-2',
				content: 'This has improved response times by 30%!',
				createdAt: '2024-03-06T09:10:00Z',
				createdBy: 'user-1',
			},
		],
		tags: ['performance', 'jwt'],
	},
	{
		id: 'item-4',
		title: 'Add rate limiting for auth endpoints',
		description: 'Implement rate limiting for authentication endpoints to prevent brute force attacks.',
		status: 'in-progress',
		priority: 'high',
		category: 'security',
		createdAt: '2024-03-08T14:20:00Z',
		updatedAt: '2024-03-12T10:30:00Z',
		createdBy: 'user-1',
		assignedTo: 'user-2',
		dueDate: '2024-03-25T00:00:00Z',
		votes: 10,
		comments: [],
		tags: ['security', 'rate-limiting'],
	},
	{
		id: 'item-5',
		title: 'Improve error messages',
		description: 'Make authentication error messages more user-friendly while maintaining security.',
		status: 'planned',
		priority: 'low',
		category: 'improvement',
		createdAt: '2024-03-10T11:00:00Z',
		updatedAt: '2024-03-10T11:00:00Z',
		createdBy: 'user-3',
		votes: 3,
		comments: [],
		tags: ['ux', 'errors'],
	},
	{
		id: 'item-6',
		title: 'Add session revocation',
		description: 'Allow users to revoke active sessions from their account settings.',
		status: 'planned',
		priority: 'medium',
		category: 'feature',
		createdAt: '2024-03-12T09:45:00Z',
		updatedAt: '2024-03-12T09:45:00Z',
		createdBy: 'user-2',
		votes: 7,
		comments: [],
		tags: ['sessions', 'security'],
	},
	{
		id: 'item-7',
		title: 'Fix password reset token expiration',
		description: "Fix a bug where password reset tokens don't expire correctly.",
		status: 'completed',
		priority: 'critical',
		category: 'bugfix',
		createdAt: '2024-03-01T08:30:00Z',
		updatedAt: '2024-03-02T14:20:00Z',
		createdBy: 'user-1',
		assignedTo: 'user-1',
		votes: 15,
		comments: [
			{
				id: 'comment-3',
				content: 'This was a critical security issue. Good catch!',
				createdAt: '2024-03-02T15:00:00Z',
				createdBy: 'user-2',
			},
		],
		tags: ['security', 'bugfix', 'tokens'],
	},
	{
		id: 'item-8',
		title: 'Add OAuth2 provider for Microsoft',
		description: 'Implement OAuth2 authentication with Microsoft accounts.',
		status: 'cancelled',
		priority: 'low',
		category: 'feature',
		createdAt: '2024-02-15T13:20:00Z',
		updatedAt: '2024-03-10T09:15:00Z',
		createdBy: 'user-3',
		votes: 4,
		comments: [
			{
				id: 'comment-4',
				content: 'This has been cancelled in favor of focusing on WebAuthn support.',
				createdAt: '2024-03-10T09:15:00Z',
				createdBy: 'user-1',
			},
		],
		tags: ['oauth', 'microsoft'],
	},
	{
		id: 'item-9',
		title: 'Improve documentation for JWT implementation',
		description: 'Add more detailed documentation for the custom JWT implementation.',
		status: 'in-progress',
		priority: 'medium',
		category: 'documentation',
		createdAt: '2024-03-15T10:30:00Z',
		updatedAt: '2024-03-15T10:30:00Z',
		createdBy: 'user-2',
		assignedTo: 'user-2',
		dueDate: '2024-03-30T00:00:00Z',
		votes: 6,
		comments: [],
		tags: ['documentation', 'jwt'],
	},
	{
		id: 'item-10',
		title: 'Add two-factor authentication',
		description: 'Implement TOTP-based two-factor authentication.',
		status: 'completed',
		priority: 'high',
		category: 'feature',
		createdAt: '2024-02-10T09:00:00Z',
		updatedAt: '2024-03-01T15:45:00Z',
		createdBy: 'user-1',
		assignedTo: 'user-1',
		votes: 20,
		comments: [
			{
				id: 'comment-5',
				content: 'This was a great addition to our security features!',
				createdAt: '2024-03-01T16:00:00Z',
				createdBy: 'user-3',
			},
		],
		tags: ['security', '2fa', 'totp'],
	},
]

export const mockRoadmapLanes: RoadmapLane[] = [
	{
		id: 'planned',
		title: 'Planned',
		items: mockRoadmapItems.filter((item) => item.status === 'planned'),
	},
	{
		id: 'in-progress',
		title: 'In Progress',
		items: mockRoadmapItems.filter((item) => item.status === 'in-progress'),
	},
	{
		id: 'completed',
		title: 'Completed',
		items: mockRoadmapItems.filter((item) => item.status === 'completed'),
	},
	{
		id: 'cancelled',
		title: 'Cancelled',
		items: mockRoadmapItems.filter((item) => item.status === 'cancelled'),
	},
]

// Mock current user - for demo purposes
export const mockCurrentUser: RoadmapUser = mockUsers[0] // Admin user
