#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint

# Generate barrel files
npm run barrels

# Add any changes to barrel files
git add "$(git diff --name-only --cached | grep 'index.ts$')" 